// node chatgpt-app/stock-semaphore/test.mjs  (no dependencies)
import assert from 'node:assert/strict';
import fs from 'node:fs';
import w, { classify, semaphore, WIDGET_HTML } from './worker.js';
const c = (o, locale) => classify(o, locale);
assert.equal(c({ name: 'a', stock: 0 }).color, 'red');
assert.equal(c({ name: 'a', stock: 1, red_at: 1 }).color, 'red');
assert.equal(c({ name: 'a', stock: 3, red_at: 1, low_at: 3 }).color, 'orange');
assert.equal(c({ name: 'a', stock: 9, days_since_last_sale: 45 }).color, 'black');
assert.equal(c({ name: 'a', stock: 9, price: 10, cost: 5 }).color, 'yellow');
assert.equal(c({ name: 'a', stock: 9, price: 10, cost: 8 }).color, 'green');
assert.equal(c({ name: 'a', stock: 9, expires_in_days: 2 }).color, 'red');
assert.equal(c({ name: 'a', stock: 9, days_since_last_sale: 90, expires_in_days: 6 }).color, 'orange'); // expiry is more severe than dead weight
assert.equal(c({ name: 'a', stock: 9, price: 10, cost: 2, expires_in_days: 7 }).color, 'orange');
assert.equal(c({ name: 'a', stock: 20 }).level, 3);
assert.equal(c({ name: 'a', stock: 9, days_since_last_sale: 120 }).level, 3);
assert.equal(c({ name: 'a', stock: 9 }, 'es-EC').label, 'Sano');
assert.equal(semaphore([{ name: 'a', stock: 9 }], 'es-EC').locale, 'es');

const call = async (m) => (await w.fetch(new Request('https://x/mcp', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(m) }))).json();
const init = await call({ jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-06-18' } });
assert.equal(init.result.protocolVersion, '2025-06-18');
const initFallback = await call({ jsonrpc: '2.0', id: 11, method: 'initialize', params: { protocolVersion: '2099-01-01' } });
assert.equal(initFallback.result.protocolVersion, '2025-11-25');
const listed = await call({ jsonrpc: '2.0', id: 2, method: 'tools/list' });
assert.equal(listed.result.tools[0].name, 'stock_semaphore');
assert.equal(listed.result.tools[0]._meta.ui.resourceUri, 'ui://widget/stock-semaphore-v2.html');
assert.equal(listed.result.tools[0]._meta['openai/outputTemplate'], 'ui://widget/stock-semaphore-v2.html');
const r = await call({ jsonrpc: '2.0', id: 3, method: 'tools/call', params: { name: 'stock_semaphore', _meta: { 'openai/locale': 'es-EC' }, arguments: { items: [{ name: 'Tazas', stock: 12, price: 10, cost: 7 }, { name: 'Velas', stock: 0 }] } } });
assert.equal(r.result.structuredContent.items[0].name, 'Velas');
assert.equal(r.result.structuredContent.locale, 'es');
assert.match(r.result.content[0].text, /urgentes/);
const resource = await call({ jsonrpc: '2.0', id: 4, method: 'resources/read', params: { uri: 'ui://widget/stock-semaphore-v2.html' } });
assert.equal(resource.result.contents[0].mimeType, 'text/html;profile=mcp-app');
assert.equal(resource.result.contents[0]._meta.ui.prefersBorder, true);
assert.deepEqual(resource.result.contents[0]._meta.ui.csp.connectDomains, []);
assert.match(WIDGET_HTML, /Privacy & terms/);
assert.match(WIDGET_HTML, /Privacidad y términos/);
assert.match(WIDGET_HTML, /demo code 456/);
const source = fs.readFileSync(new URL('./worker.js', import.meta.url), 'utf8');
assert.doesNotMatch(source, /console\.(log|info|warn|error)/);
assert.doesNotMatch(source, /localStorage|indexedDB|caches\./);
console.log('stock-semaphore: OK');
